108 place an order
muhammad-ahmad45/e_commerce pull request #8
Opened 2023-10-12 14:57 UTC by muhammad-ahmad45

2023-10-17 11:37 UTC, abdullah-xprolabs commented on .byebug_history
Remove this File.

2023-10-17 11:37 UTC, abdullah-xprolabs commented on app/controllers/line_items_controller.rb
Remove this Byebug

2023-10-17 11:39 UTC, ghost commented on app/controllers/orders_controller.rb
> +
Fix this.

2023-10-17 11:39 UTC, abdullah-xprolabs commented on app/controllers/orders_controller.rb
> +>>>>>>> parent of 4f0e174 (Order: added place an order functionality)
Fix this too.

2023-10-17 11:40 UTC, abdullah-xprolabs commented on app/javascript/cart.js
> +      url: 'line_items/52/update_quantity',
Fix the Ajax feature.

2023-10-17 11:41 UTC, abdullah-xprolabs commented on app/mailers/order_mailer.rb
> +end
Use 2 spaces for Indentation

2023-10-17 11:45 UTC, abdullah-xprolabs commented on app/views/layouts/_header.html.erb
> +        <%if current_user && (current_user.if_admin? || current_user.has_staff?) %>
Use admin? instead of if_admin? for the method name

2023-10-17 11:46 UTC, abdullah-xprolabs commented on app/views/orders/_form.html.erb
> +=======
Fix these code issues.

2023-10-17 11:46 UTC, abdullah-xprolabs commented on app/views/orders/_form.html.erb
> +    <div>
Fix this too

2023-10-17 11:48 UTC, abdullah-xprolabs commented on app/views/orders/edit.html.erb
Either use this as the edit view or delete this.
Why is this here?

2023-10-18 08:08 UTC, AyishmAziz123 commented on app/controllers/orders_controller.rb
> +    @order = Order.new(order_params)
why are we not using @cart.build_order ?

2023-10-18 08:08 UTC, AyishmAziz123 commented on app/controllers/orders_controller.rb
> +      OrderMailer.confirmation_email(@order).deliver_now
Move this to after_action

2023-10-18 08:09 UTC, AyishmAziz123 commented on app/controllers/orders_controller.rb
> +      @cart.line_items.destroy_all
are we not using dependent: :destroy for line_items association ?

2023-10-18 08:09 UTC, AyishmAziz123 commented on app/controllers/orders_controller.rb
> +    @order = Order.find(params[:id])
Move this to a before_action

2023-10-18 08:10 UTC, AyishmAziz123 commented on app/controllers/orders_controller.rb
> +      redirect_to orders_path, method: :get, notice: "Status of Order #{@order.id} is updated successfully."
Why have we used method: :get

2023-10-18 08:11 UTC, AyishmAziz123 commented on app/controllers/orders_controller.rb
> +    @order = Order.find(params[:id])
Move this to before_action as well

2023-10-18 08:13 UTC, AyishmAziz123 commented on app/models/user.rb
> +  has_many :orders
Why haven't we used dependent destroy here ?

2023-10-18 08:14 UTC, AyishmAziz123 commented on app/models/user.rb
> +    self.permissions.build(role_id: customer_role&.id)
What will happen if customer_role is nil. Will it build permissions with role_id: nil ?

2023-10-18 08:15 UTC, AyishmAziz123 commented on app/views/carts/show.html.erb
> +              <% bill = line_item.total_price %>
Should we need to eager load line_items for cart ?

2023-10-18 08:16 UTC, AyishmAziz123 commented on app/views/carts/show.html.erb
> +   <%= button_to "Check Out", new_order_path(@cart), method: :get, class: "btn btn-primary" %>
Please verify do we need to specify method: :get. If not then remove this from here

2023-10-18 08:18 UTC, AyishmAziz123 commented on app/views/devise/shared/_links.html.erb
> +        <% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
refactor `controller_name != 'passwords' && controller_name != 'registrations'`
to 
`%w[passwords registrations].exclude? controller_name`

Also move such conditions to helpers

2023-10-18 08:20 UTC, AyishmAziz123 commented on app/views/orders/_form.html.erb
> +          <%= form.hidden_field :status, value: 'dispatched' %>
Why are we sending this value from here ? Can we use default value for status in the database ?

2023-10-18 08:20 UTC, AyishmAziz123 commented on app/views/orders/_form.html.erb
> +          <% current_user.cart.line_items.each do |line_item| %>
check if we need to eager load associations here

2023-10-18 08:21 UTC, AyishmAziz123 commented on app/views/orders/_update_status.html.erb
> +<%= form_for order, url: { controller: 'orders', action: 'update', id: order.id }, method: :patch do |form| %>
can we just user order_path(order) in place of `{ controller: 'orders', action: 'update', id: order.id }`

2023-10-18 08:22 UTC, AyishmAziz123 commented on app/views/orders/edit.html.erb
> +<h1>Orders#edit</h1>
Are we using this file ?

2023-10-18 08:22 UTC, AyishmAziz123 commented on app/views/orders/index.html.erb
> +          <td><%= order.user.id %></td>
Check for n + 1 query here

2023-10-18 08:25 UTC, AyishmAziz123 commented on test/mailers/previews/order_mailer_preview.rb
> +class OrderMailerPreview < ActionMailer::Preview
Are we using this file ?

2023-10-18 08:25 UTC, AyishmAziz123 requested changes
Added some comments

2023-10-23 12:33 UTC, merged